modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "dockercomputer"
version = "${version}"
displayName = "Docker Computer Mod"
authors = "Me!"
description = '''
This is Docker Computer description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.dockercomputer]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dockercomputer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dockercomputer]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"